### ISSUE TITLE
Python 3.13 supports numpy==2.1, please upgrade numpy version

### ISSUE THREAD

**Issue by Anna-Ku** [manykarim/robotframework-doctestlibrary#100]
Hi

Python latest version doesn't support numpy<2.1, current doctest version works with numpy<2.0.
Please upgrade version.

Thanks,
Anna

**Comment by manykarim** [comment]
Thanks for creating the issue.
I'm working on a new release which will also use numpy 2.1 on Python 3.13

https://github.com/manykarim/robotframework-doctestlibrary/actions/runs/11412475564/attempts/1#summary-31758505817

Hopefully will finalize it this weekend

**Comment by Anna-Ku** [comment]
@manykarim ok, thanks!

**Comment by Anna-Ku** [comment]
@manykarim hi :), can you please estimate how much time will take to release version with numpy=2.1 support?

**Comment by manykarim** [comment]
Hi @Anna-Ku , hi @bwomsm1 ,
it's almost ready. 
https://github.com/manykarim/robotframework-doctestlibrary/actions/runs/11419156553/attempts/1#summary-31773432376
Test results on Python 3.13 look good, but as it's such a major refactoring in that release , that I was afraid to release it before my current vacation. But once I'm back on 11-Nov I'll do a prerelease within the week and do the proper release latest until 24-Nov.

**Comment by bwomsm1** [comment]
Hi @manykarim, any news regarding the fix? thank you!

**Comment by manykarim** [comment]
Hi @bwomsm1 , thanks for following up on this.
I worked on the new release last week, but there are still a few points I'm not totally happy about.

But as I see the urgency to update the dependencies and support Python 3.13 let's do the following:
- Release a new version today which will only update the dependencies and support Python 3.13
- Release the refactored version (which will also support Python 3.13) in the coming days

I think that makes more sense and will also reduce the risk of newly introduced defects due to the refactoring.

**Comment by manykarim** [comment]
I'll just wait for the tests in CI to be completed and publish the release to PyPi afterwards..
https://github.com/manykarim/robotframework-doctestlibrary/actions/runs/11888701800

**Comment by manykarim** [comment]
There's one thing that you could maybe check beforehand @bwomsm1 

Are you able to install `scikit-image` in your Python 3.13 environment?
The current stable 0.24 does not support Python 3.13 and the 0.25 is still a release candidate.
As there is no wheel for 0.24 and Python 3.13 yet, it tries to build the package from source on my machine, but it fails on my windows system.
I can see that it works in the CI Pipeline (which runs on Linux).
But I'd be interested if you're also using Windows and if you have more success installing `scikit-image` with Python 3.13.

**Comment by bwomsm1** [comment]
> scikit-image

I am on it.

**Comment by bwomsm1** [comment]
> scikit-image

hi,
I was able to install scikit-image lib
```
boazwarshawsky@qa-mv-01067 products-automation-framework % pip3 install scikit-image
Requirement already satisfied: scikit-image in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (0.25.0rc1)
Requirement already satisfied: numpy>=1.24 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from scikit-image) (2.1.3)
Requirement already satisfied: scipy>=1.10 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from scikit-image) (1.14.1)
Requirement already satisfied: networkx>=3.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from scikit-image) (3.4.2)
Requirement already satisfied: pillow>=9.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from scikit-image) (11.0.0)
Requirement already satisfied: imageio!=2.35.0,>=2.33 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from scikit-image) (2.36.0)
Requirement already satisfied: tifffile>=2022.8.12 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from scikit-image) (2024.9.20)
Requirement already satisfied: packaging>=21 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from scikit-image) (24.2)
Requirement already satisfied: lazy-loader>=0.4 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from scikit-image) (0.4)
```

**Comment by bwomsm1** [comment]
@manykarim sorry, taking my words back, after doing uninstall to `scikit-image` and then install and fail in installing the lib:
```
Found existing installation: scikit-image 0.25.0rc1
Uninstalling scikit-image-0.25.0rc1:
  Would remove:
    /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/scikit_image-0.25.0rc1.dist-info/*
    /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/skimage/*
Proceed (Y/n)? y
  Successfully uninstalled scikit-image-0.25.0rc1
boazwarshawsky@qa-mv-01067 products-automation-tests % pip install scikit-image
Collecting scikit-image
  Downloading scikit_image-0.24.0.tar.gz (22.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.7/22.7 MB 38.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      + meson setup /private/var/folders/b2/3q970w753l1_dw7ntszqqg140000gn/T/pip-install-s_qcy2od/scikit-image_2a0b04371cda48bd874f5fa038526255 /private/var/folders/b2/3q970w753l1_dw7ntszqqg140000gn/T/pip-install-s_qcy2od/scikit-image_2a0b04371cda48bd874f5fa038526255/.mesonpy-w6404pck -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/private/var/folders/b2/3q970w753l1_dw7ntszqqg140000gn/T/pip-install-s_qcy2od/scikit-image_2a0b04371cda48bd874f5fa038526255/.mesonpy-w6404pck/meson-python-native-file.ini
      The Meson build system
      Version: 1.6.0
      Source dir: /private/var/folders/b2/3q970w753l1_dw7ntszqqg140000gn/T/pip-install-s_qcy2od/scikit-image_2a0b04371cda48bd874f5fa038526255
      Build dir: /private/var/folders/b2/3q970w753l1_dw7ntszqqg140000gn/T/pip-install-s_qcy2od/scikit-image_2a0b04371cda48bd874f5fa038526255/.mesonpy-w6404pck
      Build type: native build

      ../meson.build:7:11: ERROR: Command `/private/var/folders/b2/3q970w753l1_dw7ntszqqg140000gn/T/pip-install-s_qcy2od/scikit-image_2a0b04371cda48bd874f5fa038526255/skimage/_build_utils/version.py` failed with status 127.

      A full log can be found at /private/var/folders/b2/3q970w753l1_dw7ntszqqg140000gn/T/pip-install-s_qcy2od/scikit-image_2a0b04371cda48bd874f5fa038526255/.mesonpy-w6404pck/meson-logs/meson-log.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by manykarim** [comment]
No worries, I updated the dependencies in my library with the release candidate of scikit-image 0.25.

You can install my library normally via 
pip install -U robotframework-doctestlibrary
