### ISSUE TITLE
I don´t see img in output

### ISSUE THREAD

**Issue by 12jakubpavel** [manykarim/robotframework-doctestlibrary#20]
Hi. I am not sure why, but I don´t see any img from doctestlibrary. Have you any idea whats wrong? 
I'm not sure if any folder with screenshot names existed.

![obrazek](https://user-images.githubusercontent.com/37021143/126387773-f63a9af6-5f14-445c-8fa4-6414678de93d.png)
![obrazek](https://user-images.githubusercontent.com/37021143/126387841-64e4d5e3-0a25-45a2-ab1e-0fc657916882.png)
![obrazek](https://user-images.githubusercontent.com/37021143/126388289-d3eb7d7a-cbd7-44cb-9b1b-bb53e1c90085.png)

**Comment by manykarim** [comment]
Hi Jakub,
Looking at the code in VisualTest.py, it seems like Screenshots are stored
in the screenshots/ subfolder of the current working directory. Could you
please try to create the 'screenshots' folder in the 'output' directory and
give it another try?
Will investigate a bit further tomorrow.

BR,
Many


12jakubpavel ***@***.***> schrieb am Di., 20. Juli 2021,
22:05:

**Comment by 12jakubpavel** [comment]
Hi Manykarim.

I tried that too. The folder remained, but there was nothing in it. Oh, I can see it now. Screenshots are stored in the project, but I'm creating output one folder up.

**Comment by manykarim** [comment]
The screenshots folder will always be created in the `outputdir` used by Robot Framework.
By default the outputdir is the current path from which Robot Framework was executed.
But it can be adjusted via the --outputdir command line parameter.
