### ISSUE TITLE
Argument ignore_watermarks

### ISSUE THREAD

**Issue by extmme** [manykarim/robotframework-doctestlibrary#33]
An argument ignore_watermarks is mentioned at your file Compare.robot but it is not mentioned in VisualTest documentation. 
https://github.com/manykarim/robotframework-doctestlibrary/blob/main/atest/Compare.robot

Does it miss it or is not relevant? 

Thanks.

**Comment by manykarim** [comment]
Thank you for mentioning it.
It's an argument which is no longer needed and the default value will be `False`.
It is a feature which was required for some document tests in my company which had a watermark in the middle of the page.
As it is not useful for other users, it is now disabled by default and can only be switched on via an evironment variable.
See https://github.com/manykarim/robotframework-doctestlibrary/blob/main/DocTest/VisualTest.py
`ignore_watermarks = os.getenv('IGNORE_WATERMARKS', False)`

What is basically does (when set to `True`):
If a visual difference is detected AND if there is only one single difference AND the difference is in the middle of a page and has a certain size THEN consider the visual comparison passed.

The `watermark_file` feature is more interesting for other users.
https://github.com/manykarim/robotframework-doctestlibrary#ignore-watermarks-for-visual-comparisons

**Comment by manykarim** [comment]
Now added to Keyword Documentation with v0.4.1
