### ISSUE TITLE
Possible bug - ValueError: invalid literal for int() - doctestlibrary 0.8.1

### ISSUE THREAD

**Issue by csello-landsure** [manykarim/robotframework-doctestlibrary#62]
Hi,

My team just updated our doctest library from a 2021 version (I don't have the exact version) to 0.8.1.

After upgrading, many of our tests started failing with stack traces like this:
![image](https://user-images.githubusercontent.com/92488127/212437284-629cc18c-06e5-4789-807e-b8a4c213ff09.png)

The reason I suspect a bug in either the library or one of the external assets is that the values quoted in the stack trace (values like "42.246494") are not being passed to the library by our test code. 

I looked at CompareImage.py", line 129 and noticed that the code is interacting in some way with Tesseract. As a workaround, we are now invoking "east" in the library initialization (ocr_engine=east), and now our tests are passing.

**Comment by csello-landsure** [comment]
I note that the error I am reporting in this ticket is the same one reported in the comments on https://github.com/manykarim/robotframework-doctestlibrary/issues/48

**Comment by manykarim** [comment]
Thank you for your report. I'm wondering if it's just a simple conversion problem as tesseract expects an integer for that value.
Will look into it.

**Comment by manykarim** [comment]
ok, I think I fixed that one. Strange why it didn't appear in my Unit or Acceptance Tests. Because I also have float values for confidence there. mhm.
Will release it with 0.9.0 in the next days

**Comment by csello-landsure** [comment]
@manykarim - Thank you very much. My team has come to rely on DocTest Library for many workflows, so we *really* appreciate the work you put into maintenance!

**Comment by manykarim** [comment]
Took a bit longer, but new 0.9.0 release contains that fix
